version: '3'
services:
  mysql:
    image: mysql:5.7.29
    hostname: mysql_server
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    env_file:
      - ./.env
    volumes:
      - ./data/mysql:/var/lib/mysql


